### ISSUE TITLE
add wind/3dp data import

### ISSUE THREAD

**Issue by stereoF** [heliopython/heliopy#109]

**Comment by dstansby** [comment]
Are you looking for a particular 3DP data product? Currently the particle moments (pm) product works https://heliopy.readthedocs.io/en/latest/code_ref/data/wind.html#heliopy.data.wind.threedp_pm

**Comment by stereoF** [comment]
@dstansby I'm looking for pitch angel distribution products. In IDL load_wi_sfpd loads these products.

**Comment by dstansby** [comment]
Sorry this has taken ages... it's a bit harder working on pitch angle data than simple timeseries! I'm about halfway through working out how to do this, so should have some progress soon.

**Comment by dstansby** [comment]
🎉 this should now work on the master branch, and when I release version `0.2` it will be in that. Let me know if you want any other data products adding!
