### ISSUE TITLE
Add sunspot number importing

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#273]
http://www.sidc.be/silso/datafiles

**Comment by abotiamnot** [comment]
This data import only covers on recovering information through the given sources, right?

**Comment by dstansby** [comment]
The data downloading code is designed to handle files split by year or day for example, so it looks like it won't work for the sunspot number, where they have a file that has the same name with all the data which is updated.

Code to fix this issue would probably need to keep a track of the last time the file was download, and if it was more than a day ago (say) re-download the file.

**Comment by abotiamnot** [comment]
Thanks. By the way, does the module need to have choices for the user? Or should the module always download the same data, 'Daily total sunspot number'? I'd like to work on this issue!

**Comment by abotiamnot** [comment]
@dstansby We can close this issue now!

**Comment by dstansby** [comment]
Fixed by #362
