### ISSUE TITLE
Return data that has units

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#291]
Currently all the data returned by HelioPy just returns numbers, and (hopefully!) the documentation says what units the numbers are in. AstroPy has a mature units system however, that allows data that has units attached: http://docs.astropy.org/en/stable/units/index.html

One potential problem is that pandas DataFrames do not currently work with units: https://github.com/pandas-dev/pandas/issues/10349 and **all** of HelioPy revolves around DataFrames, so this might involve finding an alternative for DataFrames. A possible alternative is AstroPy tables: http://docs.astropy.org/en/stable/table/index.html

**Comment by abotiamnot** [comment]
Assuming that we cannot work with Pandas anymore, will HelioPy migrate to AstroPy Tables entirely or will it introduce some functionality to convert DataFrames to AstroPy Tables?

**Comment by dstansby** [comment]
I am still thinking about how to do this at the moment. Sunpy has a Timeseries class that might be good to use. @cadair informs me that this will eventually morph into AstroPy tables at some point. I'll post another comment here when I have had a bit more of a think.

**Comment by abotiamnot** [comment]
By the way, the first step for this would be adding a usable units system, right?

**Comment by dstansby** [comment]
The units bit of this is definitely going to be astropy units, the hard bit is working out how to attach them to the data in the best way.

**Comment by dstansby** [comment]
🎉 this has been selected for Google summer of code, and @abotiamnot will be working on it. I'm going to target this for release 0.7; there's a few bits I want to get out before then, which will be 0.6, and then this can be the big new feature for 0.7.
