### ISSUE TITLE
Choose a CDF reader to use

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#292]
Currently HelioPy uses a copy of the cdf reader from SpacePy. This isn't ideal because we don't want to maintain our own cdf reader, and the reader should really exist in an independent package.

**Comment by dstansby** [comment]
https://github.com/rstoneback/pysatCDF looks like a good option, and is actively maintained.

**Comment by abotiamnot** [comment]
I seem to be having problems setting up the environment on my Windows. Going to install a Linux for this.

**Comment by dstansby** [comment]
Hmm not ideal then since we want to keep HelioPy windows compatible without too much trouble. There's also https://github.com/MAVENSDC/cdflib which is pure python.
