### ISSUE TITLE
Add a PEP8 checker to test suite

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#306]
Something like pytest-pep8 would be good to check that new code conforms to the PEP8 guidelines: https://pypi.python.org/pypi/pytest-pep8

**Comment by prateekiiest** [comment]
I guess https://github.com/OrkoHunter/pep8speaks is a good place to use with.
But I thing as a contributor to this project, I don't have the permission to install pep8 speaks.

You can visit the website here https://pep8speaks.com/

**Comment by dstansby** [comment]
I think something that runs on the continuous integration services instead of a github comment bot would be better (I'm not a big fan of pep8 speaks to be honest).
