### ISSUE TITLE
Add some more spice kernels to data loading

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#326]
Ideas include:

- [ ] ACE
- [ ] Juno

EDIT: everything here would be good to add: https://naif.jpl.nasa.gov/naif/data_archived.html

**Comment by abotiamnot** [comment]
@dstansby Here's a list of some more SPICE kernels, should we add them as well? 

https://naif.jpl.nasa.gov/naif/data_archived.html

**Comment by dstansby** [comment]
Nice find! Adding all of those would be great.

**Comment by abotiamnot** [comment]
I think we should add several different categories for get_kernel function, like in this link here, 

ftp://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/info/intrdctn.html

Under the SPICE kernels, there's like a few different kernels available. SPKs allow the user to find ephemeris data, PCKs are filled with planetary constants like geometry and different others for the rest.

We can add a variety of kernels within the program. Every single spacecraft in that list has a variety of kernels available.

I think spicepy can load different types of kernels. In their own example, they've used LSK, PCK etc.

**Comment by dstansby** [comment]
I'm going to close this, and we can just add the kernels one by one as they are requested.
