### ISSUE TITLE
Skip missing data files instead of trowing URLError

### ISSUE THREAD

**Issue by jpomoell** [heliopython/heliopy#341]
When loading data for a longer time period (e.g. a month), it would perhaps be better that `heliopy.data.helper.load` skips missing data files instead of stops. For instance, 

`data = heliopy.data.wind.swe_h1(datetime.datetime(1997, 6, 10), datetime.datetime(1997, 6, 30))`

fails since e.g. the data file for June 18 (ftp://spdf.gsfc.nasa.gov/pub/data/wind/swe/swe_h1/1997/wi_h1_swe_19970618_v01.cdf) does not exist.

Perhaps it would be possible that the user could provide a kwarg to the data loader to tell that missing files should be skipped?

P.S. Great initiative, I am really excited about heliopy!

**Comment by dstansby** [comment]
Thanks for reporting this! Other methods definitely skip missing data, so I'm not sure why WIND doesn't.

**Comment by dstansby** [comment]
I've been meaning to refactor all the data loading for a while, so thanks for nudging me. This means that all the downloading/saving goes through the same code, so is consistent across functions. It'll probably take me a while to convert everything over, but when I do I'll put out version 0.5.0 with it all done!

**Comment by jpomoell** [comment]
That sounds like a good approach, thanks!
