### ISSUE TITLE
Urrlib file and helper.py in two different directories

### ISSUE THREAD

**Issue by prateekiiest** [heliopython/heliopy#355]
Hi, @dstansby 

I recently installed heliopy on my local machine. 

When I import like this

`from heliopy.data import artemis`

I get an error saying 

```
C:\Users\pratik\Anaconda2\lib\site-packages\heliopy\data\helper.py in <module>()
      2 import os
      3 import sys
----> 4 from urllib.error import URLError
      5 import urllib.request as urlreq
      6 import ftplib

ImportError: No module named error
```

I worked with checking the urrlib file path
```
import urllib
print(urllib)
```
and I get this `<module 'urllib' from 'C:\Users\pratik\Anaconda2\lib\urllib.pyc'>` indicating heliopy data tries to access urrlib which is completely in a different directory.

I don't know why this occurred. Is it due to some fault when installing heliopy .

Also I checked `helper.py` on the repository. https://github.com/heliopython/heliopy/blob/master/heliopy/data/helper.py#L6

The libraries imported and that on my helper.py file in my local machine is completely different.

**Comment by Mianto** [comment]
@prateekiiest I guess you haven't actually installed heliopy in your local machine. urllib is python module which is installed on your local machine and heliopy is not installed, You can first install it by using 
``pip install heliopy``
Or you can actually build it from source by following the steps given in [docs](http://docs.heliopy.org/en/stable/guide/installing.html)

**Comment by dstansby** [comment]
What version of python are you using, and what version of heliopy is installed?

**Comment by prateekiiest** [comment]
@Mianto I have already done that, other wise I would have got an error `No module named heliopy`

**Comment by prateekiiest** [comment]
@dstansby 

py2.7.

Heliopy : Latest one

**Comment by dstansby** [comment]
HelioPy doesn't support python 2, so you'll have to install python 3. It looks like the source distribution isn't tagged properly, which is why it's installing on python 2, I'll try and fix it in the future so there's a more obvious error.

**Comment by prateekiiest** [comment]
ok, I get it. Thanks for letting me know about it
