### ISSUE TITLE
Add sunspot number import and plotting example

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#365]
#362 added the ability to import sunspot numbers; it would be good to have an example in the gallery to demonstrate this. Just a simple import the data and plot it would be good. The most similar example is probably `examples/plot_importing_data.py` if inspiration is needed.

**Comment by abotiamnot** [comment]
I've added a PR for this, please take a look! #366

**Comment by abotiamnot** [comment]
@dstansby We can close this PR now! Thanks for merging!

**Comment by dstansby** [comment]
Fixed by #366
