### ISSUE TITLE
Add a travis cron job

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#397]
It would be good to add a daily travis cron job, that runs the build each day, to check for server changes on a regular basis. It probably only needs to be a single job (the python 3.6 build). I think this can be done just by editing the `.travis.yml` file.

**Comment by Mianto** [comment]
Doing cron jobs by using `.travis.yml` is an open [issue.](https://github.com/travis-ci/travis-ci/issues/9162) I think it has to be done manually.

**Comment by abotiamnot** [comment]
Like @Mianto said, I guess it has to be done manually through the TravisCI's website, but we can add another [email](https://docs.travis-ci.com/user/notifications)notification using TravisCI's notification on the .yml file.

**Comment by dstansby** [comment]
Great, I've added this using travis settings.
