### ISSUE TITLE
Adding more data sources

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#403]
I guess we can add several more spacecraft modules, like DSCOVR. I will a checklist here to keep a track of them. 

- [ ] DSCOVR
- [ ] GOES 13
- [ ] GOES 14
- [ ] OMNI

Well, almost anything here, 

https://omniweb.sci.gsfc.nasa.gov/ftpbrowser/

**Comment by dstansby** [comment]
I'm going to close this to add more specific issues for each mission.
