### ISSUE TITLE
Inconsistencies in returned data

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#416]
There are some inconsistencies in the data, so we need to get them fixed! 

- [x] heliopy.data.artemis.fgm returns two 'time' columns. The first index column needs to have time header, and the last time column needs to be dropped.
- [x] heliopy.data.imp.mag320ms returns two 'time' columns. The first index column needs to have time header, and the last time column needs to be dropped.
- [x] heliopy.data.imp.mitplasma_h0 's time index column lacks 'time' header
- [x] heliopy.data.wind.mfi_h0 does not return all the columns ( not sure if this is a problem, but just putting it up just in case! )
- [ ] heliopy.data.wind.swe_h1 returns negative years.

For the last one, there are,

> Epoch, Time_PB5, NUM_PTS, BF1, BRMSF1, BGSM, BRMSGSM, BGSE, BRMSGSE, DIST, PGSM, PGSE, SGSM, SGSE, DB_SC, TILTANG, RANGE_I, RANGE_O, SPC_MODE, MAG_MODE, Epoch3, Time3_PB5, NUM3_PTS, B3F1, B3RMSF1, B3GSM, G3RMSGSM, B3GSE, B3RMSGSE, Epoch1, Time1_PB5, NUM1_PTS, B1F1, B1RMSF1, B1GSM, B1RMSGSM, B1GSE, B1RMSGSE, DIST1, P1GSM, P1GSE, S1GSM, S1GSE, ZERO_I, SENS_I, AMPL_I, ORTH_I, PAYLD_I, FLAG_I, ZERO_O, SENS_O, AMPL_O, ORTH_O, PAYLD_O, FLAG_O, label_time, format_time, unit_time, label_bgsm, label_bgse, label_bgsmr, label_bgser, label_dbsc, label_pgsm, label_pgse, cartesian  

The [README ](https://spdf.gsfc.nasa.gov/pub/data/wind/mfi/data_overview.txt)file says, 

> The parameters picked up from the originally submitted CDF files
> for the 1-min ASCII files are: 
> 
> year,month,day,hour,minute,second
> bxgse,bygse,bzgse,bygsm,bzgsm,btotal
> bxgsmrms,bygsmrms,bzgsmrms,btotalrms
> number-of-points
> pxgse,pygse,pzgse,pygsm,pzgsm  (p = s/c position)

**Comment by abotiamnot** [comment]
Really confusing. I understand that the data with three dimensions are vector data, but still, I don't understand the other variables, like which single dimensional data is the 'btotal'. I think just adding the total magnetic field magnitude btotal (?) would be enough. I will take a look at it again, and hopefully, manage to understand this!

**Comment by dstansby** [comment]
I think `mfi_h0` should return all the columns.
