### ISSUE TITLE
Convert non-CDF functions to use units

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#435]
- [x] cassini.mag_hires
- [x] imp.mag15s 
- [x] ulysses.fgm_hires

These are the functions that require being converted into units manually.

**Comment by dstansby** [comment]
Looks like this list could do with an update; https://github.com/heliopython/heliopy/issues/433 has a list of functions that are converted to `util.process` so far.

**Comment by abotiamnot** [comment]
Yep! I'm keeping the [Trello Board](https://trello.com/c/UAme93r1/5-convert-non-cdf-functions-to-use-units) updated. I will update it here as well!

**Comment by dstansby** [comment]
These all seem to be done now 👍
