### ISSUE TITLE
Use something other than .hdf files for saving data

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#442]
HDF5 is becoming proprietry: https://www.hdfgroup.org/solutions/what-does-the-enterprise-support-edition-mean-for-the-community-edition/

We should look for an alternative file type to save the pandas dataframes to file.

**Comment by abotiamnot** [comment]
There's a Bcolz library in Python. [I found it here.](http://alimanfoo.github.io/2016/04/14/to-hdf5-and-beyond.html) Can you take a look at this?

**Comment by dstansby** [comment]
The list of filetypes supported by pandas is here: https://pandas.pydata.org/pandas-docs/stable/io.html so I think we should choose one of them.

**Comment by dstansby** [comment]
HDF files are probably fine for now.
