### ISSUE TITLE
Modify SunPy TimeSeries to make getting units easier

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#443]
I've opened an issue here about this: https://github.com/sunpy/sunpy/issues/2605 - maybe you could give it a go @abotiamnot ?

**Comment by abotiamnot** [comment]
To get separate quantities, one can also do this, timeseries_data.quantity('colname')[index]


This does seem a bit tedious, and it would be a lot more flexible if one could simply do what timeseries_data['colname'][index]. What do you think?

**Comment by abotiamnot** [comment]
Made a PR, referencing to the same. https://github.com/sunpy/sunpy/pull/2643

**Comment by dstansby** [comment]
I think this is okay now - I put an example of how to access data in the HelioPy docs, and it seems fairly simple.
