### ISSUE TITLE
Define a custom units dictionary for CDF UNITS

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#472]
Now units are automatically being extracted from CDF files (🎉 ) there's a few that aren't being recognised: https://travis-ci.org/heliopython/heliopy/jobs/384678290#L1254

It would be good to have a dictionary that maps the ones that aren't converted automatically to the right quantity. e.g. `'sec'` can be mapped to `u.s`.

**Comment by abotiamnot** [comment]
There's a lot of entries, I think we can't add them into the util function. I'm considering making a different Python file for the units, which can be imported, and then will be used alongside astropy units
