### ISSUE TITLE
Files not being closed properly

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#473]
I think this is related to the units we've been implementing. 
![image](https://user-images.githubusercontent.com/36379971/40611178-e95e034e-6292-11e8-87e1-06cf8faf93c2.png)

These files have manual units, and seem to be having some problems with closing the files. I think this comes under Units too!

**Comment by dstansby** [comment]
Good spot!

**Comment by abotiamnot** [comment]
Getting same warning in the PR I made, so it is a bug!
