### ISSUE TITLE
Add documentation for new units functionality

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#491]
All the new units work will need quite a bit of documentation. I think this breaks down into:

- [ ] A "What's new" entry
- [ ] Some longer discussion on the "Data import" page of exactly what the data returned is by the import methods, including links to the relevant Sunpy/Astropy/Pandas documentation (http://docs.heliopy.org/en/latest/data/index.html)
- [ ] Check that all the converted functions have the correct docstrings for the returns section

**Comment by abotiamnot** [comment]
Should this example be removed? http://docs.heliopy.org/en/stable/auto_examples/plot_multi_index.html#sphx-glr-auto-examples-plot-multi-index-py
