### ISSUE TITLE
Fix missing unit warnings

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#492]
There are lots of warnings about missing units: https://travis-ci.org/heliopython/heliopy/jobs/391243174#L1250

I think the way to fix these is to correctly assign units that the automatic CDF unit converter doesn't pick up. This might be more easily solved by #472

**Comment by dstansby** [comment]
Looks like `wind.swe_h1` still has some warnings: https://travis-ci.org/heliopython/heliopy/jobs/395764080#L1313

**Comment by dstansby** [comment]
Updated list of missing unit warnings: https://travis-ci.org/heliopython/heliopy/builds/407705536#L1258

**Comment by abotiamnot** [comment]
There are some new warnings that need to be fixed, so I think this issue should be reopened?

**Comment by dstansby** [comment]
Looking at this: https://cdaweb.sci.gsfc.nasa.gov/misc/NotesW.html#WI_PM_3DP I would guess they're dimensionless, though I'm not sure; lets just put them is as dimensionless for now.
