### ISSUE TITLE
Add functionality to return spacecraft coordinates as functions of time

### ISSUE THREAD

**Issue by namurphy** [heliopython/heliopy#500]
We've recently been using heliopy to work with _Ulysses_ data, and one of the challenges has been working with, transforming, and understanding the spacecraft's coordinates.  We can get `hlat` and `hlon` from `swoops_ions` in `heliopy.data.ulysses`, but I had a harder time getting coordinates from the output of the SWICS functions.  

It would be really helpful to have functions that return the coordinates of spacecraft such as Ulysses as functions of time in a format that makes it easy to transform to different coordinate systems (e.g., [Ulysses orbital information](https://www.cosmos.esa.int/web/ulysses/orbit#)).  I imagine this would be really helpful for other spacecraft as well.  It would also be helpful to provide an example of working with Ulysses coordinates in the documentation for the module.

Many thanks!
-Nick

**Comment by dstansby** [comment]
There's a couple of different things that could be helpful here:

- It is currently possible to use the `heliopy.data.spice` module to get a Ulysses SPICE kernel, and then use this with `heliopy.spice` to generate positions in different cooridnate systems. See http://docs.heliopy.org/en/latest/auto_examples/plot_spice_orbit.html#sphx-glr-auto-examples-plot-spice-orbit-py for an example that uses Solar Orbiter - if you have any problems with that example feel free to open a new issue.
- There's a plan to implement a lot of coordinate systems support in `heliopy.coordinates`, but I don't really have time to work on it at the moment. Eventually this should provide what you want within python (#323)

**Comment by abotiamnot** [comment]
The SWICS source file actually has no longitude or latitude data, hence there are no such hlong/hlan or any coordinate system for instance in the imported data.

**Comment by dstansby** [comment]
@namurphy did you have much luck with using the `heliopy.spice` module?

**Comment by namurphy** [comment]
@dstansby - We ended up being able to get the coordinate information that we needed from the Ulysses data archive, so we didn't end up using `heliopy.spice`.  I'll be sure to remember that in case something like this comes up again.  I'm also excited about the future `heliopy.coordinates` subpackage.  Thanks!
