### ISSUE TITLE
Add Solar Orbiter data import

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#515]
A placeholder for when data (finally!) exists.

**Comment by abotiamnot** [comment]
Can you add this to Units?

**Comment by dstansby** [comment]
Sorry, should have mentioned that Solar Orbiter doesn't launch for a couple of years, but I opened this as a placeholder.

**Comment by sashank27** [comment]
@dstansby I guess now is the time for this 😅

**Comment by ZigongXu** [comment]
I think the Solar orbiter data will available soon this year! Hope this place will work again.!

**Comment by johan12345** [comment]
The first Solar Orbiter Low-Latency data is now publically available at https://www.cosmos.esa.int/web/solar-orbiter/access-to-solar-orbiter-low-latency-data

**Comment by dstansby** [comment]
Yep, I'm slowly working on getting the low latency data added to heliopy. If I haven't finished in a couple of weeks, feel free to nudge me by adding a comment on this issue!
