### ISSUE TITLE
Add a python 3.7 travis build

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#519]
Python 3.7 is out 🎉 so we should add a python 3.7 build to travis, and think about moving the documentation and windows build to 3.7 too.

**Comment by abotiamnot** [comment]
YAY!! Python 3.7! What should we do in this though?

**Comment by dstansby** [comment]
I think all that needs doing is modifying `.travis.yml` to add a python 3.7 section. I'm not sure if travis has python 3.7 available yet, but it's worth trying.
