### ISSUE TITLE
Functions re-download already existing files

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#544]
Just adding this for future references since we should fix this too.

**Comment by dstansby** [comment]
Are there specific functions that do this?

**Comment by abotiamnot** [comment]
I didn't make a list, will do and update this issue.

**Comment by dstansby** [comment]
Is this fixed now?

**Comment by abotiamnot** [comment]
Going to give all modules a try and get back to you.

**Comment by abotiamnot** [comment]
Tried them! All are working well.
