### ISSUE TITLE
Add logo page

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#559]
We should add a logo page to the docs w/ logos that work on both black and white, so if anyone wants to use the logo it is easy to access.

**Comment by xypnox** [comment]
Hi @dstansby I would like to work on this issue. Can you suggest the correct place where the logos should be added in the docs? Inside a subtopic or as a page in itself separate from others.

**Comment by dstansby** [comment]
A new page in `doc/source/guide/` would be good! Let me know if you have any other questions.

**Comment by dstansby** [comment]
Fixed by #653
