### ISSUE TITLE
Add CDAS RESTful web service support

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#562]
https://cdaweb.sci.gsfc.nasa.gov/WebServices/REST/ - this is a much better way to download data than we are currently using, and would automatically give access to ALL of NASAs data on the SPDF.

See https://bitbucket.org/isavnin/ai.cdas/src/8006f8b6de2566d91214d336d49d0c9f1d0e96cc/src/ai/cdas.py for some code that already does this, that we could possibly use.

Edit: I have started this here: #575. Other data download modules that can be moved to CDAS are

- [ ]  artemis
- [x] cassini
- [x] imp
- [x] messenger
- [x] mms
- [ ] wind

**Comment by abotiamnot** [comment]
Sounds great! I think we can work on this after 0.6V!

**Comment by dstansby** [comment]
This is basically done for MMS 🎉

**Comment by dstansby** [comment]
I'm going to close this since it's now fairly easy to extend support for further cdas available datasets.
