### ISSUE TITLE
Bepi Colombo SPICE

### ISSUE THREAD

**Issue by cmoestl** [heliopython/heliopy#629]
Hi, 

please add this spice file to get the bepi-colombo position:

https://repos.cosmos.esa.int/socci/projects/SPICE_KERNELS/repos/bepicolombo/browse/kernels/spk/bc_mpo_fcp_00040_20181020_20251102_v01.bsp

ciao chris

**Comment by dstansby** [comment]
👍 , in the mean time if you download the file locally you can use `heliopy.spice.furnish(fname)` to load it into spice.
