### ISSUE TITLE
Cassini SPICE Kernel 

### ISSUE THREAD

**Issue by RichardHaythorn** [heliopython/heliopy#634]
Please add the Cassini SPICE Kernel 

https://naif.jpl.nasa.gov/pub/naif/pds/data/co-s_j_e_v-spice-6-v1.0/cosp_1000/aareadme.htm

**Comment by dstansby** [comment]
It looks like most of the trajectory kernels live here: https://naif.jpl.nasa.gov/pub/naif/pds/data/co-s_j_e_v-spice-6-v1.0/cosp_1000/data/spk/ , but there's a lot of them! Is there any chance you could work out which subset of these are needed to cover the whole cassini mission?

**Comment by RichardHaythorn** [comment]
I could have a look, I'm still figuring out SPICE myself. I can't see any overlaps with the SCPSE files though on first glance

**Comment by dstansby** [comment]
Did you make any progress working out what the complete set is?

**Comment by RichardHaythorn** [comment]
Im not entirely sure but I think you'll need:
- all the R_SCPSE/RB_SCPSE/RU_SCPSE files for the core and extended mission.
- "co_1997288_97318_launch_v1.bsp ", "co_1997319_99311_i_cru_v1.bsp ", "co_1999312_01066_o_cru_v1.bsp" to fill in the pre-mission section 

Possibly also "180927AP_RE_90165_18018.bsp  "

**Comment by RichardHaythorn** [comment]
So I've been working on this and I think I've got the full mission working.
 However 175 SPICE kernels are required (no meta-kernels exist as far as I know).
These total ~1GB. Meaning the download time is quite long.

Possibilities:
1) leave full set as it is, long and lengthy
2) split into cruise phase and years, quicker but documentation heavy

**Comment by dstansby** [comment]
I propose adding the cruise kernel to HelioPy, since that's easy and a reasonable download, and adding a link to the remaining kernels if someone wants to download them. Does that sound okay?
