### ISSUE TITLE
Automatically detect STEREO-A kernels to be downloaded

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#657]
Currently the STEREO-A spice kernels are hardcoded, but their names keep changing. It should be possible to list the files in the directory instead to get the right filenames each time.

**Comment by ritzvik** [comment]
@dstansby May I work on this? It would be helpful if you could show where to implement the change.

**Comment by ritzvik** [comment]
> @dstansby May I work on this? It would be helpful if you could show where to implement the change.

Sorry for bothering. I actually figured out where you want the change. It would be helpful if you can mention the files with extensions which need to be picked up. And just for clarification, do you want files to dynamically fetched from https://naif.jpl.nasa.gov/pub/naif/generic_kernels/ for a start?

**Comment by dstansby** [comment]
Thanks for offering to help!

The kernels are all downloaded from https://sohowww.nascom.nasa.gov/solarsoft/stereo/gen/data/spice/depm/ahead/ - currently the filenames are hardcoded at

https://github.com/heliopython/heliopy/blob/3aa0e51603c4282387fb97a9d75a0f09badd1798/heliopy/data/spice.py#L70-L84

so the idea is to replace this list with an automatic listing based in what is in the remote directory linked above. Does that help? Let me know if you have any other questions.

**Comment by ritzvik** [comment]
It may need a HTML parser like `beutifulsoup` or `requests-html`, but I think that would increase dependencies.

So, I am thinking of getting the HTML text and then search separate the `.bsp` string from it.

Suggestions @dstansby ?

**Comment by ritzvik** [comment]
This code is able to fetch the names of files. Should I integrate like this?
```
import requests
r = requests.get('https://sohowww.nascom.nasa.gov/solarsoft/stereo/gen/data/spice/depm/ahead/')
file_list = [S.split('"')[1] for S in r.text.split('href') if '.bsp' in S]
```

**Comment by dstansby** [comment]
Looks good to me
