### ISSUE TITLE
Results not consistent with SSWIDL?

### ISSUE THREAD

**Issue by AndresMiguelReyes** [heliopython/heliopy#659]
I want to use heliopy to replace SSWIDL, but it seems that the results are not consistent, is there some time assumption in **generate_positions** not mentioned in the documentation? I know IDL converts the string to UTC.

Here is the IDL command I used with SSWIDL:
```
IDL> STATE = GET_STEREO_COORD('2018-12-01T00:00:00', 'A', SYSTEM='GSE', TARGET='Earth')
IDL> STATE
       176268388.45850757       140183920.22549492       287477.09458222985
      -1.4732182738576807      0.30762263291625946    -0.025424267765099984
```
I tried to replicate this using heliopy:
```
import heliopy.data.spice as spicedata
import heliopy.spice as spice
from datetime import datetime, timedelta
import astropy.units as u
import numpy as np

kernels = spicedata.get_kernel('stereo_a')
kernels += spicedata.get_kernel('stereo_a_pred')
spice.furnish(kernels)
sta = spice.Trajectory('Stereo Ahead')
starttime = datetime(2018, 12, 1, 0, 0, 0)
times = []
times.append(starttime)
starttime += timedelta(hours=1)
times.append(starttime)
sta.generate_positions(times,'Earth','GSE')
print("{}\t{}\t{}".format(sta.x[0],sta.y[0],sta.z[0]))
```
The result was:
> 175975085.18622038 km	140239680.1247754 km	287983.5894397944 km

Both of these calls are using Stereo-A to find the position of Earth at 2018-12-01T00:00:00 UTC in the GSE coordinate system. At least that is my intention.

The SSWIDL command returns values in km so we can calculate the relative error:
x relative error:
```
>>> abs(176268388.45850757- 175975085.18622038)/176268388.45850757
0.001663958437767369
```
y relative error:
```
>>> abs(140183920.22549492-140239680.1247754)/140183920.22549492
0.0003977624480096938
```
z relative error:
```
>>> abs(287477.09458222985-287983.5894397944)/287477.09458222985
0.0017618616130117139
```

Could this inconsistency be due to my SSWIDL and heliopy using different spice kernels?

PS: I edited stereo A in spacecraft_kernels in spice.py to match the list of .bsp files available at [https://sohowww.nascom.nasa.gov/solarsoft/stereo/gen/data/spice/depm/ahead/](https://sohowww.nascom.nasa.gov/solarsoft/stereo/gen/data/spice/depm/ahead/)

**Comment by dstansby** [comment]
The relevant lines in `HelioPy` are
https://github.com/heliopython/heliopy/blob/626b44d67bffe3a0e8cc749b1556e760accb5ebb/heliopy/spice.py#L100-L101
which calls `spiceypy` (https://spiceypy.readthedocs.io/en/master/documentation.html#spiceypy.spiceypy.spkezr), which should call the SPICE toolkit directly.

Is there a way to check what the relevant call is in SSWIDL, to see if there are any differences?

**Comment by AndresMiguelReyes** [comment]
I looked into it further and came to the conclusion that the SPICE kernel that my SSWIDL is using is out of date. Both SSWIDL and HelioPy call the spkezr function.
