### ISSUE TITLE
SPICE ECLIPJ2000 to HEE / HEEQ coordinates

### ISSUE THREAD

**Issue by cmoestl** [heliopython/heliopy#667]
Concerning spice spacecraft and planet positions - is there a direct way to convert from ECLIPJ2000 to HEE / HEEQ? With the Earth position in ECLIPJ2000 I can convert the PSP/Bepi/SolO positions to HEE by projections in the HEE system and then there are transforms to HEEQ according to Hapgood (1992), see also http://www.mssl.ucl.ac.uk/grid/iau/extra/local_copy/SP_coords/helitran.htm
but its cumbersome.

**Comment by dstansby** [comment]
It is possible to generate the coordinates directly in `HEE` or `HEEQ` by using the `frame` argument to [`generate_positions()`](https://docs.heliopy.org/en/stable/api/heliopy.spice.Trajectory.html#heliopy.spice.Trajectory.generate_positions). It would be good to document what systems are available though.

**Comment by cmoestl** [comment]
I see that 

`psp.generate_positions(psp_time,'Sun',frame=framenames)
`

works with the inertial framenames under "Appendix. ``Built in'' Inertial Reference Frames  " at
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/frames.html#Inertial%20Frames

but HEE, HEEQ are not included; 
`psp.generate_positions(psp_time,'Sun',frame='HEEQ')
`
leads to an SPICE(UNKNOWNFRAME) error.

**Comment by dstansby** [comment]
`heliopy.spice` should also automatically load [this file](https://naif.jpl.nasa.gov/pub/naif/pds/data/nh-j_p_ss-spice-6-v1.0/nhsp_1000/data/fk/heliospheric_v004u.tf), which contains HEEQ and HEE coordinates. What version of HelioPy are you running - maybe upgrading to the latest version will fix it?

**Comment by cmoestl** [comment]
Yes indeed upgrading 0.6.5 from 0.6.3 (sorry, thought I upgraded recently but probably missed it) allows to use HEE/HEEQ as frame, thanks much! 
But one problem stil persists: `psp.generate_positions(psp_time,'Sun','HEEQ')` works only until Oct 9 2018. If I force to use the file `spice.furnish('spp_nom_20180812_20250831_v034_RO1_TCM1.bsp')` then using `psp.generate_positions(psp_time,'Sun','HEEQ')` works for longer times (instead of `psp_kernel=spicedata.get_kernel('psp')`) and then `spice.furnish`. How is it decided which spice file to use automatically?

**Comment by dstansby** [comment]
The trajectories are now split into "actual" and "predicted" ones; you should be able to get the predicted trajectory by loading `psp_pred` (see http://docs.heliopy.org/en/stable/data/spice.html#predicted-trajectories)

**Comment by cmoestl** [comment]
Great thanks, everything works now!

**Comment by dstansby** [comment]
🎉
