### ISSUE TITLE
Time for import data (omni, mms, etc.)

### ISSUE THREAD

**Issue by dupuisIRT** [heliopython/heliopy#680]
Hi, 

I am interested in a lot of features provided by heliopy.data, however their imports are so slow. 
For instance time python -c 'import heliopy.data.omni' returns
real	0m19.572s
user	0m4.331s
sys	0m1.440s

Almost 20s. I think the problem comes from heliopy.data.util and in particular from the import of sunpy.timeseries. 

Do you think it would be beneficial to optimize this part of the code by avoiding a systematic import of sunpy timeseries ?

**Comment by dstansby** [comment]
Are they still slow after the first time you have run the import? The first time python generates cached files that should speed it up subsequently, for example the first time (after install) I do `time python -c 'import sunpy.timeseries'` I get:
```
real	0m12.536s
user	0m1.404s
sys	0m0.566s
```
but thereafter I get something like
```
real	0m1.275s
user	0m1.248s
sys	0m0.268s
```

That's not to say that import times could definitely be improved, I will have a look into it.

**Comment by dupuisIRT** [comment]
Ok thanks, I will try to go around, in particular for unit tests.
