### ISSUE TITLE
Replace bad data in Omni

### ISSUE THREAD

**Issue by kylermurphy** [heliopython/heliopy#683]
Is there a simple way to replace bad data with NaN within the omni routine?

**Comment by dstansby** [comment]
Ha, funny you should mention that, I fixed a bit of it just now: https://github.com/heliopython/heliopy/pull/682

If you could come up with a list of all the values that are "bad" in the OMNI data it should be fairly easy to fix the rest.

**Comment by kylermurphy** [comment]
Hi David, 

Thanks! 

The text file (ftp://spdf.gsfc.nasa.gov/pub/data/omni/low_res_omni/omni2.text) contains all of the bad data formats for the OMNI values. 

Out of curiosity (am new to Python) the how quickly do the fixes here get pushed to conda-forge?

**Comment by dstansby** [comment]
I've just fixed this, and released a new version of HelioPy. It should be out on conda-forge in the next 24 hours 🎉
