### ISSUE TITLE
Debian Package for HelioPy

### ISSUE THREAD

**Issue by shreyasbapat** [heliopython/heliopy#684]
In progress to #415 : 

I have started packaging HelioPy for Debian. Aside from having it in Debian directly, it would also automatically migrate to Ubuntu, Mint etc. And you would get build tests on many platforms, and continuous integration tests for free.

There are some points to consider.

- The packaging should happen in its own repository on [Salsa](https://salsa.debian.org), not on your main Github repository. The reason is that we want to have it easy accessible by the Debian developers (f.e. to create a new Debian revision in urgent cases). This also makes it easier for us to gather information from all repositories of Debian software. This all is however very organized, no need to worry that someone just takes over and makes changes that you don't want. The repository also has a specific layout.
So, we have created a repository for the same in Salsa: https://salsa.debian.org/debian-astro-team/heliopy 

- Discussions happen preferably in public on our [mailing list](https://lists.debian.org/debian-astro); you however can also contact [me directly](mailto:shreyas@einsteinpy.org) if you like that more. 

- We are currently already in a Freeze for the next (Debian 10/Buster) release, so heliopy won't be included there directly. It will however be (when it is ready then) in the 19.10 Ubuntu release, and in Debian 11. It can also be "backported" to Debian 10 so that those users can easily install it there. We can go through this process once we have it uploaded.

Finally, I have filed an ITP in Debian Bug Tracking System: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928699 

I may need a help or two for packaging heliopy. I will use this issue to reach out to you. I hope that is fine :sweat_smile: .

**Comment by dstansby** [comment]
Thanks for doing this! Please do let me know if you come across any issues or have any questions.

**Comment by shreyasbapat** [comment]
Hi @dstansby , just to make sure, all the source files have the same licence, i.e GPL-3.0 right?

**Comment by dstansby** [comment]
Yep, everything is GPL-3.0

**Comment by shreyasbapat** [comment]
The tests are not passing during packaging due to a missing package :  cdflib
https://github.com/MAVENSDC/cdflib

**Comment by shreyasbapat** [comment]
I am sorry for the delay. I am on it!

**Comment by dstansby** [comment]
Did you get anywhere with this in the end? I'm tempted to close it, since having another package just means something else to maintain, and it's pretty easy to install since currently heliopy is a pure python package.
