### ISSUE TITLE
MMS bug with probe 0/4

### ISSUE THREAD

**Issue by dupuisIRT** [heliopython/heliopy#716]
Hi,

With heliopy 0.6.7, I got trouble with probe 0/4. The docstring indicates:
Probe number, must be 1, 2, 3, or 4

Or, the method  _validate_probe(probe) defines allowed_probes as [str(i) for i in range(4)], so it is ['0', '1', '2', '3'].

In final, when I want to download probe '4', mms.py raise an error and for probe '0', the download starts but no data are available, as probe '0' does not exist.

(I have no problem with probe '1', '2', and '3')

**Comment by dstansby** [comment]
Fixed by #719
