### ISSUE TITLE
Add functionality to MMS

### ISSUE THREAD

**Issue by argallmr** [heliopython/heliopy#717]
I work on the MMS team and have a module [pymms](https://github.com/argallmr/pymms/tree/master/pymms) that makes full use of the MMS data API, including logging in to the team site, accessing file information, and obtaining ancilliary data products like definitive attitude and emphemeris files. I would like to help incorporate this functionality into heliopy.data.mms.

**Comment by dstansby** [comment]
Thanks for offering to help! In the current un-released version of HelioPy (to become 0.8.0) I've changed the code a bit to make it much easier to add new sources. https://docs.heliopy.org/en/latest/api/heliopy.data.util.Downloader.html#heliopy.data.util.Downloader describes a `Downloader` object, that can be sub-classed to provide new data sources. As an example, https://github.com/heliopython/heliopy/blob/ef1497b1a2ca91ef03e63d33417bca5ebba91fda/heliopy/data/cdasrest.py#L60-L106 shows how it was implemented for another service.

Hopefully that should provide a good starting point? Let me know if you have any questions!

**Comment by argallmr** [comment]
Excellent! I will look into it.

**Comment by argallmr** [comment]
A few questions about util.Downloader:

1. Why aren't interval or starttime and endtime attributes of the class? starttime and endtime are datetime values, whereas interval is a sunpy.time.TimeRange. starttime and endtime could be attributes that set interval internally.

2. Downloader.intervals: MMS file names contain only the start time of the data interval. Should the end time of the sub-interval related to that file be None? Or possibly either the endtime or the start time of the next data file, whichever is sooner? Neither of those would be true end times of the sub-interval.

3. Downloader.local_dir: MMS data directory naming convention is root/[directories]/year/month[/day]. Multiple local directories can exist for a given interval. Should all directories be returned? (I do not recommend the convention currently implemented by heliopy because directories can become extremely large.)

4. Downloader.fname: Does this return a single file name for a single sub-interval returned by Downloader.intervals, or does it return all files between starttime and endtime (comment says "filename" -- singular).

5. How do I know which directory is the root for heliopy data?

**Comment by argallmr** [comment]
I think I am on the right track but feel we should have a discussion about what the MMS API can do and what heliopy.data.util.Downloader expects.

**Comment by dstansby** [comment]
In answer to the questions:

1. I can't think of a good reason either way, so I guess it could be possible to let `starttime` and `endtime` be attribues.
2. The end time of the interval should be the start time of the next data file.
3. I think `Downloader.local_dir` is flexible enough to go down `year/month/day` in the directory structure, since you can write a function to take the small interval, extract the year/month/day, and then construct a directory with that information
4. It returns a single file name, since there must be a one-to-one mapping between intervals and files
5. If you run `import heliopy; print(heliopy.config)` that should print out your configuration, including the download directory.

I hope those answers help? Let me know if you have any more questions!

**Comment by argallmr** [comment]
Some progress:

```
from heliopy.data import mms
import datetime as dt
starttime = dt.datetime(2019, 4, 15, 0, 0, 0)
endtime = dt.datetime(2019, 4, 15, 23, 59, 59)
api = mms.MMSDownloader('mms1', 'fgm', 'brst', 'l2', start_date=starttime, end_date=endtime)
intervals = api.intervals()
local_dirs = [api.local_dir(interval) for interval in intervals]
file_names = [api.fname(interval) for interval in intervals]
local_files = [api.download(interval) for interval in intervals]
896kB [00:00, 2.36MB/s]                                                                                                                              
1.62MB [00:00, 6.72MB/s]                                                                                                                             
1.25MB [00:00, 6.73MB/s]                                                                                                                             
1.88MB [00:00, 13.2MB/s]                                                                                                                             
1.50MB [00:00, 17.4MB/s]
```

Note that for any given interval, the SDC returns all files and directories within that interval. So, the intervals, local_dir, fname, and download methods call more generic methods by similar (plural, e.g. fnames) names.

I still have to look more into how heliopy loads data before implement the load_local_file method.

**Comment by argallmr** [comment]
I followed cdasrest.load_local_file and now loading a single local file works.

`
import datetime as dt
from heliopy.data import mms

sc = 'mms1'
instr = 'fgm'
mode = 'srvy'
level = 'l2'
starttime = dt.datetime(2017, 7, 11, 0, 0, 0)
endtime = dt.datetime(2017, 7, 14, 23, 59, 59)

api = mms.MMSDownloader(sc, instr, mode, level, start_date=starttime, end_date=endtime)
intervals = api.intervals()
file = api.download(intervals[0])
data = api.load_local_file(intervals[0])

print(data)
                            mms1_fgm_b_gse_srvy_l2_0  mms1_fgm_b_gse_srvy_l2_1  ...  mms1_fgm_etemp_srvy_l2  mms1_fgm_mode_srvy_l2
Time                                                                            ...                                               
2017-07-11 00:00:10.897071                 40.989471                 17.935209  ...               19.445099               7.999895
2017-07-11 00:00:11.022073                 40.980347                 17.939367  ...               19.445099               7.999895
2017-07-11 00:00:11.147074                 40.990417                 17.932871  ...               19.445099               7.999895
2017-07-11 00:00:11.272076                 40.988770                 17.919222  ...               19.445099               7.999895
2017-07-11 00:00:11.397077                 40.984055                 17.923159  ...               19.445099               7.999895
...                                              ...                       ...  ...                     ...                    ...
`

**Comment by dstansby** [comment]
👋 Thanks for opening this issue. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this issue know.

**Comment by dstansby** [comment]
I'm currently in the process of archiving heliopy, so as such am going to close this feature request.
