### ISSUE TITLE
FTP to HTTP site

### ISSUE THREAD

**Issue by nate-snaptech** [heliopython/heliopy#718]
The ftp site has had its data files removed or not publically available. Needs to change to http://helios-data.ssl.berkeley.edu/data/

**Comment by dstansby** [comment]
Is there a particular data product that this isn't working for?

**Comment by nate-snaptech** [comment]
Yeah the alpha-fit repository. Effectively it was going to download the corefit csvs but nothing was being downloaded. When I checked the ftp site the files were no longer there. Also for without the corefit remote files the alpha-fit would not generate. I changed to http site and this solved the issue.

**Comment by dstansby** [comment]
Annoyingly I think downloading the `mag_4hz` data needs to use the ftp site to read filenames; I think the solution to this is asking for the ftp side to be fixed.

**Comment by dstansby** [comment]
I *think* this got fixed at some point - feel free to comment if it's still an issue!

**Comment by nate-snaptech** [comment]
Yeah I believe so. Thank you.
