### ISSUE TITLE
Managing distribution functions on MMS

### ISSUE THREAD

**Issue by hbreuill** [heliopython/heliopy#737]
When trying to retrieve MMS 3D distribution functions using the mms.fpi_dis_dist function, for example as follows:

```
import heliopy.data.mms as mms
import matplotlib.pyplot as plt
from datetime import datetime

starttime = datetime(2018, 4, 8, 0, 0, 0)
endtime = datetime(2018, 4, 8, 0, 1, 0)


mms_data = mms.fpi_dis_dist('1', 'fast', starttime, endtime)#, product_string="")

print(mms_data.data['mms1_dis_energy_fast_1'])
```

It returns all energy channels but not the actual distribution function. Additionally, I've noticed that functions cdf2df and pitchdist_cdf2df are not suited for MMS distribution function 4D ( *f(time,energy,polar_angle,azimuthal_angle) ) array (cdf2df handles one-dimensional dataset and pitchdist_cdf2df handles 3D datasets).

Therefore, we (@dupuisIRT) developed a simple function to retrieve the 4D array (based on pitchdist_cdf2df function), such as:

```
from datetime import datetime
import pandas as pd
import cdflib


def distfunc_cdf2df(cdf, starttime, endtime, timekey, distkey, energykey, thetakey, phikey):
    """
    Converts cdf file of a 4D distribution function to a pandas dataframe.
    MultiIndexing is used as the distribution function is essentially a 4D
    dataset *f(time, energy, theta, phi)*. See
    http://pandas.pydata.org/pandas-docs/stable/advanced.html#multiindex-advanced-indexing
    for more information.
    This has been constructed for importing MMS 3D particle distribution functions.
    
    Parameters
    ----------
    cdf : cdf
        Opened cdf file.
    timekey : string 
        The cdf key for the timestamps. The array access by timekey must
        have shape `(n)`
    energykey : string
        The cdf key for the energy values. The array accessed by energykey
        must have shape `(m)` or `(a, m)` where `a` can be anything. If it
        has shape `(a, m)`, we assume energies measured don't change, and
        take the first row as the energies for all times.
    thetakey : string
        The cdf key for the pixel zenith angles. The array must
        have shape `(l)`
    phikey : string
        The cdf key for the azimuth angles. The array must
        have shape `(k)`
    
    Returns
    -------
    df : :class:`pandas.DataFrame`
        Data frame with MultiIndex.
    """
    
    # Define extracted start and end time
    tstart=list(starttime.timetuple())
    tend=list(endtime.timetuple())
    
    # Get variables from cdf file
    time = cdf.varget(timekey,None,tstart,tend)[...]
    energy = cdf.varget(energykey,None,tstart,tend)[...]
    theta = cdf.varget(thetakey,None,tstart,tend)[...]
    phi = cdf.varget(phikey,None,tstart,tend)[...]
    dist = cdf.varget(distkey,None,tstart,tend)[...]
    
    # If energy is 2D, just take first dimension (energies are assumed constant)
    if len(energy.shape) == 2:
        energy = energy[0, :]
    
    # Define names and labels of the df 
    names=['time','energy','theta','phi']
    labels=[time,energy,theta,phi]
    
    # Create the MultiIndex df
    index = pd.MultiIndex.from_product(labels,names=names)
    dist=dist.flatten()
    data=pd.DataFrame(dist,index=index,columns=['df'])
    data = data.sort_index()
    
    return data
```

 What about using this kind of function to generalize the cdf2df function to multidimensional arrays? An would it be worth to pass these MultiIndex dataframes to SunPy TimeSeries or better to return them directly as MultiIndex dataframes (or even better xarrays)?

**Comment by dstansby** [comment]
This sounds good! I think it would be best to create a new`DistributionFuncitons` object, that for now can just store an `xarray` (I played around with `xarray` a while ago, and it seems like a much better way to do multi-dimensional indexing than pandas multiindex). In the future it could then be possible to add funcitonality to `DistributionFuncitons`, for example to easily plot energy spectra.

Would you be happy creating a pull request to create the new class, and then add the above code to make the MMS distribution function code? I'm happy to answer any questions!

**Comment by dupuisIRT** [comment]
Dear @dstansby,

We (with @hbreuill and others) are precisely using xarray in the python package we are developing, mainly to deal with multi-dimensional dataframe. 
We will try to do our best to create the new class with such features.

**Comment by dstansby** [comment]
Hi @dupuisIRT did you make much progress with this? I'm thinking of having a go myself in the near future, but don't want to duplicate any effort.

**Comment by dupuisIRT** [comment]
Hi @dstansby , 
We made some progress with @hbreuill , mainly by adding a cdf2xr function in data/util.py.
For the moment we did not open PR as docstrings and tests are not ready. However, we managed to download some distributions for mms and cluster.

We will do our best to open a PR soon.

**Comment by dupuisIRT** [comment]
Hi @dstansby , I think this issue can be closed:
https://gitlab.com/aidaspace/heliopy_multid

**Comment by dstansby** [comment]
👋 @hbreuill (I'm not sure how of this you know so apologies for any repeptition) - as @dupuisIRT has mentioned, he's started a new package for multi-D data at https://gitlab.com/aidaspace/heliopy_multid since I don't have the time to review/help with stuff at the moment. As such I'm going to close this and the other multi-D related PRs and issues.

If you have anything you want to change with heliopy's currently 1D data capabilities please keep submitting issues and PRs though!
