### ISSUE TITLE
MMS downloading raises astropy warnings

### ISSUE THREAD

**Issue by dupuisIRT** [heliopython/heliopy#745]
Downloading MMS data raises the following warning
```
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
```

Astropy raises this warning in the magic method \__\_bool\_\_ for astropy quantity:
https://github.com/astropy/astropy/blob/master/astropy/units/quantity.py 

In heliopy, I think it can come from the cfd_units method in data/utils: https://github.com/heliopython/heliopy/blob/master/heliopy/data/util.py

with ```if temp_unit is None``` but I have to double check

**Comment by dstansby** [comment]
Hmm, I have a feeling I fixed this a while back; what version of HelioPy are you using?

**Comment by dupuisIRT** [comment]
I am using 0.8.0

**Comment by dstansby** [comment]
Could you post a short and self contained example that reproduces the warnings?

**Comment by dupuisIRT** [comment]
Here is an example

```python
from datetime import datetime
import heliopy.data.mms as mms


start_time = datetime(2018, 4, 8, 0, 0, 0)
end_time = datetime(2018, 4, 8, 0, 1, 0)

product_list =  {'B0_vec': 'mms{0}_fgm_b_{1}_srvy_l2'.format('1', 'gse')}

mms_df = mms.download_files('1', 'fgm', 'srvy',
                            start_time, end_time,
                            product_string='',
                            product_list=product_list)
```

and the warning:
```
'list' object has no attribute 'shape' - Variable label_b_gse
'list' object has no attribute 'shape' - Variable label_b_gsm
'list' object has no attribute 'shape' - Variable label_b_dmpa
'list' object has no attribute 'shape' - Variable label_b_bcs
'list' object has no attribute 'shape' - Variable label_r_gse
'list' object has no attribute 'shape' - Variable label_r_gsm
'list' object has no attribute 'shape' - Variable represent_vec_tot
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]

```

**Comment by dstansby** [comment]
It's taking me quite a while (> 5 mins) to run that download, so I've aborted; I don't suppose you know of a smaller file that raises the same warning?

**Comment by dupuisIRT** [comment]
It is strange as the time interval is only 1 minute. I may try to find another interval.

**Comment by dstansby** [comment]
I'm going to close this since I can't reproduce; if you can find another example where the warning appears please post it and re-open this!
