### ISSUE TITLE
Generalise parker spiral to out of the ecliptic

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#790]
Currently the `ParkerSpiral` object only works in the ecliptic, it should be generalised to work for non-zero latitudes.

**Comment by anthony-vo** [comment]
I want to work on this. However, one of the assumptions of the parker spiral is that solar projectiles remain moving in a straight line after they have left the corona. So the latitude is the same everywhere on each parker spiral. Can you clarify what you want?
