### ISSUE TITLE
Heliopy cdf import fails with numpy>=1.16

### ISSUE THREAD

**Issue by tlml** [heliopython/heliopy#808]
When reading data originating from cdas, cdflib fails in varget (demonstration code below). This stems to change in numpy flags in 1.16, heliopy works wine with numpy version 1.15. Should the requirements be set to require numpy=1.15 until the matter is resolved?

I have put up an issue to cdflib on the matter, hopefully it will be resolved soon!

--- Sample code ---
from datetime import datetime, timedelta
import heliopy.data.wind as wind

starttime = datetime(2016, 2, 1, 0, 0, 0)
endtime = starttime + timedelta(hours=2)

data = wind.mfi_h0(starttime, endtime)

--- Sample output ---
ValueError                                Traceback (most recent call last)
<ipython-input-2-63cdd4ae2902> in <module>
      6 endtime = starttime + timedelta(hours=2)
      7 
----> 8 data = wind.mfi_h0(starttime, endtime)
      9 

~\Projects\heliopyorig\heliopy\heliopy\data\wind.py in mfi_h0(starttime, endtime)
     45     units = {'BGSEa_0': u.nT, 'BGSEa_1': u.nT, 'BGSEa_2': u.nT}
     46     return _wind(starttime, endtime, identifier, units=units,
---> 47                  intervals='daily')
     48 
     49 

~\Projects\heliopyorig\heliopy\heliopy\data\wind.py in _wind(starttime, endtime, identifier, badvalues, units, intervals)
     25     else:
     26         dl.intervals = dl.intervals_monthly
---> 27     return dl.load(starttime, endtime)
     28 
     29 

~\Projects\heliopyorig\heliopy\heliopy\data\util.py in load(self, starttime, endtime)
     87                     continue
     88 
---> 89             data.append(self.load_local_file(interval))
     90             if use_hdf:
     91                 data[-1].to_hdf(hdf_path, 'data', mode='w', format='f')

~\Projects\heliopyorig\heliopy\heliopy\data\cdasrest.py in load_local_file(self, interval)
    104         cdf = util._load_cdf(local_path)
    105         return util.cdf2df(cdf, index_key='Epoch',
--> 106                            badvalues=self.badvalues)
    107 
    108 

~\Projects\heliopyorig\heliopy\heliopy\data\util.py in cdf2df(cdf, index_key, dtimeindex, badvalues, ignore)
    740     # Extract index values
    741     try:
--> 742         index_ = cdf.varget(index_key)[...][:, 0]
    743     except IndexError:
    744         index_ = cdf.varget(index_key)[...]

C:\Users\Timo\Anaconda3\envs\heliopy\lib\site-packages\cdflib\cdfread.py in varget(self, variable, epoch, starttime, endtime, startrec, endrec, record_range_only, inq, expand, to_np)
    571                     if name.strip().lower() == variable.strip().lower():
    572                         if (self.cdfversion == 3):
--> 573                             vdr_info = self._read_vdr(position)
    574                         else:
    575                             vdr_info = self._read_vdr2(position)

C:\Users\Timo\Anaconda3\envs\heliopy\lib\site-packages\cdflib\cdfread.py in _read_vdr(self, byte_loc)
   1402         if pad_bool:
   1403             byte_stream = vdr[coff:]
-> 1404             pad = self._read_data(byte_stream, data_type, 1, num_elements)
   1405 
   1406         return_dict = {}

C:\Users\Timo\Anaconda3\envs\heliopy\lib\site-packages\cdflib\cdfread.py in _read_data(self, byte_stream, data_type, num_recs, num_elems, dimensions)
   1920             dt = np.dtype(dt_string)
   1921             ret = np.frombuffer(byte_stream, dtype=dt, count=num_recs*num_elems)
-> 1922             ret.setflags('WRITEABLE')
   1923 
   1924         if squeeze_needed:

ValueError: cannot set WRITEABLE flag to True of this array

**Comment by dstansby** [comment]
This looks potentially like a `cdflib` issue (I have seen your other issue over on the `cdflib` repo). What version of cliflib do you have installed? I think there have been some recent versions with bugs in them that don't play well with HelioPy, but the most recent version *should* be fine.

**Comment by tlml** [comment]
Oops, it seems that I had an old one, sorry about the noise... Works well with the most recent versions. Teaches me to keep things consistent...
