### ISSUE TITLE
Pycharm debug not working due to imp.py

### ISSUE THREAD

**Issue by D-DePablos** [heliopython/heliopy#832]
Pycharm debugger attempts to import new_module from imp.py, a python base library. This interferes with the imp.py spacecraft.

ImportError: cannot import name 'new_module' from 'imp' ({...}/heliopy/heliopy/data/imp.py)

**Comment by dstansby** [comment]
Could you post the full error trace and not just the last line?

**Comment by D-DePablos** [comment]
{...}}/Python/miniconda3/bin/python {...}}/Python/pycharm-2019.2.3/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 39140 --file {...}}/PycharmProjects/heliopy/heliopy/data/imp.py
pydev debugger: process 1809 is connecting

Connected to pydev debugger (build 192.7142.42)
Traceback (most recent call last):
  File "{...}}/Python/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2108, in <module>
    main()
  File "{...}}/Python/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2099, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "{...}}/Python/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 1327, in run
    m = save_main_module(file, 'pydevd')
  File "{...}}/Python/pycharm-2019.2.3/helpers/pydev/_pydevd_bundle/pydevd_utils.py", line 40, in save_main_module
    from imp import new_module
ImportError: cannot import name 'new_module' from 'imp' ({...}}/PycharmProjects/heliopy/heliopy/data/imp.py)

Process finished with exit code 1

**Comment by dstansby** [comment]
I don't think it's possible to do a straight name change, as that would break a lot of code. Could deprecate `imp` though, and choose another module name, but I'm not sure what to choose?

I think it might also be worth reporting this upstream in the PyCharm bug tracker, as they could change their relative import (`from imp import new_module`) to an absolute import I think.

**Comment by dstansby** [comment]
I'm going to close this as I don't think it's fixable on the heliopy side.

**Comment by D-DePablos** [comment]
Thanks.

By the way, do you handle your imports from neighbouring packages?

**Comment by dstansby** [comment]
What do you mean by neighbouring packages? If they have the same name you can do `import name as othername`, for one of them to have it accessible under `othername`.
