### ISSUE TITLE
Work out how sunpy Carrington coordinates correspond to SPICE IAU_SUN coordinates

### ISSUE THREAD

**Issue by dstansby** [heliopython/heliopy#910]
Currently in `heliopy.spice` there is an association of some SPICE frames with `sunpy` coordinate frames:
https://github.com/heliopython/heliopy/blob/f468ac16355d1dc212d14a88ccb8e83055f1442f/heliopy/spice/spice.py#L12-L14
This allows one to calculate a set of coordinates using SPICE and get the results as an astropy `SkyCoord`.

As of https://docs.sunpy.org/en/stable/code_ref/coordinates/carrington.html#sunpy-coordinates-carrington we now need to associate an observer with the `HeliographicCarrington` coordinates. At a guess we should set the observer to be at the Solar radius distance, but this should be properly investigated before being implemented.

@ayshih maybe you know the right choice to make off the top of your head? No worries if not!

**Comment by ayshih** [comment]
Yes, setting a (fake) observer to be on the solar surface would be equivalent to turning off the light-travel-time correction.

Incidentally, `HeliographicCarrington` used to bake in a light-travel-time-to-Earth correction and a stellar-aberration correction, unlike instantaneous (or "true") Carrington coordinates, so I think your current mapping is inaccurate regardless.  Do you test the accuracy of these mappings against transformations in SPICE?

**Comment by dstansby** [comment]
No, I never did test the accuracy, and naively just assumed they were the same. I'll build in some tests to check that SPICE and sunpy coordinates (the coordinates heliopy is transforming to) are consistent.

Thanks for the clarification on setting the observer.

**Comment by dstansby** [comment]
Fixed by #911, which includes a test to make sure that SPICE and sunpy ephemeris functions agree.
