### ISSUE TITLE
WIND mfi_h0

### ISSUE THREAD

**Issue by RL4215** [heliopython/heliopy#933]
When the interval spans two days, but the duration is below 24hours it only loads one of the days. i.e. I want data from 2020/7/29 21:00 to 2020/7/30 16:00 but it only gives me up to 2020/7/29 23:59. However, if I ask for 2020/7/29 15:00 it gives me all the data. Probably to do with how daily_intervals works.

**Comment by dstansby** [comment]
Thanks for opening the issue! Could you post a short and self contained bit of code that demonstrates the issue?

**Comment by RL4215** [comment]
I have tracked it back to sunpy's get_dates() function inside Downloader.intervals_daily()

`
import sunpy
#this period is above 24 hours
starttime_correct = datetime(2020, 1, 1, 12)
endtime_correct = datetime(2020, 1, 2, 13)
interval_correct = sunpy.time.TimeRange(starttime_correct, endtime_correct)
daylist_correct = interval_correct.get_dates()

#this period is below 24 hours
starttime_broken = datetime(2020, 1, 1, 12)
endtime_broken = datetime(2020, 1, 2, 11)
interval_broken = sunpy.time.TimeRange(starttime_broken, endtime_broken)
daylist_broken = interval_broken.get_dates()

print(daylist_correct)
print(daylist_broken)`

**Comment by dstansby** [comment]
Looks like that's a bug in sunpy - could you report it upstream at https://github.com/sunpy/sunpy/issues?

**Comment by RL4215** [comment]
Ok done, not sure how to link it to this issue. 

https://github.com/sunpy/sunpy/issues/4527

**Comment by dstansby** [comment]
This should be fixed once a new bugfix release of sunpy is done.
