### ISSUE TITLE
SOLO Spice link is broken and no errors are thrown

### ISSUE THREAD

**Issue by STBadman** [heliopython/heliopy#937]
It appears the link to the most recent SOLO spice kernel has been placed behind an account login page ( https://repos.cosmos.esa.int/socci/projects/SPICE_KERNELS/repos/solar-orbiter/raw/kernels/spk/solo_ANC_soc-orbit_20200210-20301120_L015_V1_00024_V01.bsp ) and the effect is when you run `heliopy.data.spice.get_kernel('solo')`, the login webpage (html) is downloaded and named to the relevant .bsp file so no errors are thrown, and further when you furnish this kernel, there are also no errors even though nothing is correctly loaded.

So fixes to suggest :
* Find a link to a SOLO kernel which can be directly downloaded
* Find a way to validate when downloaded if what has been received is the expected filetype
* Find a way for spice.furnish to verify that the kernel is the expected filetype and that spice data has been loaded correctly

**Comment by AthKouloumvakos** [comment]
I think that the official distribution site of the operational kernels for ESA's missions is the following:
ftp://spiftp.esac.esa.int/data/SPICE/  so for the SOLO spice kernels is: ftp://spiftp.esac.esa.int/data/SPICE/SOLAR-ORBITER/
Another option is from nascom: https://sohowww.nascom.nasa.gov/solarsoft/so/gen/data/sunspice/ , note that bsp files are located in /orbit directory in this case.

**Comment by dstansby** [comment]
Thanks for the detailed report, looking into this now.

**Comment by dstansby** [comment]
So I can't find a good way to validate that a file is a valid `.spk` kernel - I don't know if anyone can find anything? I might raise an issue/feature request to spiceypy.

As a stopgap I'll fix the solar orbiter kernel though.

**Comment by dstansby** [comment]
Actually, I think I managed to do some kernel validation in https://github.com/heliopython/heliopy/pull/941, so just the solar orbiter kernel link needs fixing now.

**Comment by STBadman** [comment]
I see it. It tells the user the architecture type is wrong. I'm guessing you want to leave the SPICE error handling API as exposed as possible? I do think it would be a little cleaner if heliopy could simply tell the user that `get_kernel` failed, and so the saved / downlaoded kernel file is most likely corrupted

**Comment by dstansby** [comment]
Thanks for reporting, I think this is all fixed now and I've released version 0.15.0. I didn't have time to fix the lack of nice error; PRs welcome to have a nicer error than the slightly cryptic one at the moment.
