### ISSUE TITLE
Add ability to download Proba-2 in-situ DSLP data

### ISSUE THREAD

**Issue by JonCook** [heliopython/heliopy#945]
Hello @dstansby - as mentioned here are the details for accessing Proba-2 in-situ DSLP data:

An example query:
- http://p2sa.esac.esa.int/p2sa-sl-tap/tap/sync?REQUEST=doQuery&LANG=ADQL&FORMAT=JSON&PHASE=RUN&QUERY=SELECT * FROM p2sa.v_file WHERE  (file_date >= '2014-10-01 00:00:00')   AND   (file_date <= '2014-10-31 00:00:00')   AND   (file_type  in  ('DSLP_DERIVED'))  ORDER BY file_date ASC

There is also the file_type 'DSLP_CALIBRATED' which I presume are some calibration files. Not sure if they are also of interest.

In both cases, this will give you a vo-table json file with the metadata required to then download the files:

```
{
  "metadata": [
    {
      "name": "calibrated",
      "datatype": "BOOLEAN"
    },
    {
      "name": "extension",
      "datatype": "VARCHAR"
    },
    {
      "name": "file_date",
      "datatype": "TIMESTAMP",
      "xtype": "adql:TIMESTAMP"
    },
    {
      "name": "file_name",
      "datatype": "VARCHAR"
    },
    {
      "name": "file_oid",
      "datatype": "INTEGER"
    },
    {
      "name": "file_path",
      "datatype": "VARCHAR"
    },
    {
      "name": "file_size",
      "datatype": "BIGINT"
    },
    {
      "name": "file_type",
      "datatype": "VARCHAR"
    },
    {
      "name": "instrument_name",
      "datatype": "VARCHAR"
    },
    {
      "name": "instrument_oid",
      "datatype": "INTEGER"
    },
    {
      "name": "processing_level",
      "datatype": "VARCHAR"
    }
  ],
  "data": [
    [
      "false",
      "CDF",
      "2014-10-01 00:00:00.0",
      "DERIVED_SLPA_20141001.cdf",
      "136478",
      "\\/p2sa\\/p2saps\\/science\\/dslp\\/dslp_derived\\/2014\\/10",
      "19815408",
      "DSLP_DERIVED",
      "DSLP",
      "3",
      "N\\/A"
    ],
    [
      "false",
      "CDF",
      "2014-10-01 00:00:00.0",
      "DERIVED_SLPB_20141001.cdf",
      "136479",
      "\\/p2sa\\/p2saps\\/science\\/dslp\\/dslp_derived\\/2014\\/10",
      "19788276",
      "DSLP_DERIVED",
      "DSLP",
      "3",
      "N\\/A"
    ],
...
```
I think you can ignore most of it and if you prefer only select on the fields you want in the original query which will reduce the size of the json if you see what I mean.

You can then use the file_oid or the file_name to download the data. The file_name is probably more obvious to the naked eye e.g:

- http://p2sa.esac.esa.int/p2sa-sl-tap/data?retrieval_type=PRODUCT&QUERY=SELECT+*+FROM+p2sa.file+where+file_oid++in+%28136483%29

- http://p2sa.esac.esa.int/p2sa-sl-tap/data?retrieval_type=PRODUCT&QUERY=SELECT+*+FROM+p2sa.file+where+file_name='DERIVED_SLPB_20141001.cdf'

The DSLP data is between 2009 and 2016.

Any doubts, please let me know. You have my contact details. I wouldn't mind having a go at this one but probably won't have time in the next couple of weeks.

Thanks
Jonathan

**Comment by dstansby** [comment]
👋 Thanks for opening this issue. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this issue know.

**Comment by dstansby** [comment]
I'm currently in the process of archiving heliopy. Since data discovery/download has been replaced by code in sunpy, I've transferred this issue across to the sunpy repository.
