### ISSUE TITLE
Add ability to download SOHO in-situ data

### ISSUE THREAD

**Issue by JonCook** [heliopython/heliopy#946]
Hello @dstansby - as mentioned here are the details for accessing SOHO in-situ data:
 
For SOHO, there are 3 experiments measuring in-situ data CELIAS, COSTEP and ERNE. But two other experiments measure locally global irradiance or spectral solar irradiance and from GOLF irradiance around the sodium line, all are time series.

- CELIAS, in particular, its Proton Monitor instrument for proton density and temperature and the Solar EUV Monitor for Solar EUV flux:
  - Solar EUV flux at 15 seconds and 1 day cadence, from the SEM detector
  - Solar wind parameters at either 30 seconds, 5 minutes or Carrington Rotation cadence, from the Proton Monitor detector

Two sample requests here:
- http://ssa.esac.esa.int/ssa/aio/metadata-action?RESOURCE_CLASS=OBSERVATION&SELECTED_FIELDS=OBSERVATION&QUERY=(INSTRUMENT.NAME=='CELIAS'+AND+OBSERVING_MODE.NAME=='STOF')+AND+OBSERVATION.BEGINDATE>'2020-01-01'+AND+OBSERVATION.BEGINDATE<'2020-02-01'&RETURN_TYPE=JSON&PAGE=1&PAGE_SIZE=1000
- http://ssa.esac.esa.int/ssa/aio/metadata-action?RESOURCE_CLASS=OBSERVATION&SELECTED_FIELDS=OBSERVATION&QUERY=(INSTRUMENT.NAME=='CELIAS'+AND+OBSERVING_MODE.NAME=='PM')+AND+OBSERVATION.BEGINDATE>'2009-01-01'+AND+OBSERVATION.BEGINDATE<'2009-02-01'&RETURN_TYPE=JSON&PAGE=1&PAGE_SIZE=1000

In the meta-data JSON response:
```
{
     "OBSERVATION.BEGINDATE":"2020-01-19 00:56:01.0",
     "OBSERVATION.CALIBRATED":"false",
     "OBSERVATION.ENDDATE":"2020-01-20 00:56:13.0",
     "OBSERVATION.FILEFORMAT":"CDF",
     "OBSERVATION.FILENAME":"SO_CEL_STOF_SEM_LA_V02-20200119_v01.cdf",
     "OBSERVATION.FILEPATH":"/ssa/sps/science/celias/stof/2020",
     "OBSERVATION.FILESIZE":130644,
     "OBSERVATION.ID":194152814,
     "INSTRUMENT.NAME":"CELIAS",
     "SCIENCE_OBJECT.NAME":"Solar Wind",
     "OBSERVATION.OBSERVATIONTYPE":"Solar EUV Monitor",
     "OBSERVATORY.NAME":"SOHO",
     "OBSERVING_MODE.NAME":"STOF",
     "OBSERVATION.PROCESSINGLEVEL":"L0_RawData",
     "OBSERVATION.SCIENCEOBJECTIVE":"-",
     "OBSERVATION.WAVELENGTHRANGE":"-",
     "STUDY.ID":"-",
     "STUDY.NAME":"-",
     "STUDY.BEGINDATE":"-",
     "STUDY.ENDDATE":"-",
     "STUDY.STUDY_OID":"-",
     "CAMPAIGN.ATTACHMENTS":"-",
     "CAMPAIGN.BEGINDATE":"-",
     "CAMPAIGN.COMMENT":"-",
     "CAMPAIGN.ENDDATE":"-",
     "CAMPAIGN.COORDINATOR":"-",
     "CAMPAIGN.NAME":"-",
     "CAMPAIGN.NUMBER":"-",
     "CAMPAIGN.OBJECTIVE":"-",
     "CAMPAIGN.PARTICIPANTS":"-",
     "download":"http://ssa.esac.esa.int/ssa/aio/product-action?OBSERVATION.ID=194152814",
     "postcard":"http://ssa.esac.esa.int/ssa/aio/product-action?OBSERVATION.ID=194152814&RETRIEVALTYPE=POSTCARD",
     "details":"http://ssa.esac.esa.int/ssa/aio/metadata-action?OBSERVATION.ID=194152814&RESOURCE_CLASS=CELIAS_OBSERVATION&SELECTED_FIELDS=CELIAS_OBSERVATION&RETURN_TYPE=JSON"},
...
```
- Then you can use the download attribute to download the product in question e.g: http://ssa.esac.esa.int/ssa/aio/product-action?OBSERVATION.ID=194152814 - this will give you the data file e.g SO_CEL_STOF_SEM_LA_V02-20200119_v01.cdf
----
- COSTEP proton and helium fluxes for energies between 44 keV and 53 MeV
Sample request:
  - http://ssa.esac.esa.int/ssa/aio/metadata-action?RESOURCE_CLASS=OBSERVATION&SELECTED_FIELDS=OBSERVATION&QUERY=(INSTRUMENT.NAME=='COSTEP')+AND+OBSERVATION.BEGINDATE>'2009-01-01'+AND+OBSERVATION.BEGINDATE<'2009-02-01'&RETURN_TYPE=JSON&PAGE=1&PAGE_SIZE=1000

There are two detectors (EPHIN and LION) which you can use in the OBSERVING_MODE.NAME query parameter if necessary.

----
- ERNE high energy ions from a few MeV to a few 130 of MeV
Sample request:
  - http://ssa.esac.esa.int/ssa/aio/metadata-action?RESOURCE_CLASS=OBSERVATION&SELECTED_FIELDS=OBSERVATION&QUERY=(INSTRUMENT.NAME=='ERNE'+AND+OBSERVING_MODE.NAME=='HED')+AND+OBSERVATION.BEGINDATE>'2009-01-01'+AND+OBSERVATION.BEGINDATE<'2009-02-01'&RETURN_TYPE=JSON&PAGE=1&PAGE_SIZE=1000
----
- VIRGO Total solar irradiance and Spectral solar irradiance from the VIRGO experiment.
Sample request:
  - http://ssa.esac.esa.int/ssa/aio/metadata-action?RESOURCE_CLASS=OBSERVATION&SELECTED_FIELDS=OBSERVATION&QUERY=(INSTRUMENT.NAME=='VIRGO')+AND+OBSERVATION.BEGINDATE>'2009-01-01'+AND+OBSERVATION.BEGINDATE<'2009-02-01'&RETURN_TYPE=JSON&PAGE=1&PAGE_SIZE=1000
----

- GOLF key scientific data products are mission long files related to the calibrated line of sight velocities based on measurements collected either through the instrument PhotoMultiplier 1 (PM1), PhotoMultiplier 2 (PM2), or a mean of the two signals (PM1+PM2).
  - Mission long files for 4 out these experiments can be found here - https://www.cosmos.esa.int/web/soho/mission-long-files
----
General points:
- You can adjust the dates to meet your needs but please pay attention to the page and page_size parameters. if you have more than 1000 results, you'll need to manage the paging yourself to get the rest of the result items. If you omit these parameters you run the risk of getting back a very large/slow response if there are many records. Therefore, It is not recommended to omit these parameters as per the documentation at http://ssa.esac.esa.int/ssa/aio/html/metadatarequests.shtml
- You may need to filter further based on say the filename if only looking for SEM or the level. Unfortunately, the API does not support this kind of filters.

If you need other information, please let me know.
Many thanks

**Comment by dstansby** [comment]
👋 Thanks for opening this issue. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this issue know.

**Comment by dstansby** [comment]
I've moved this one across to sunpy too.
