### ISSUE TITLE
AttributeError: module 'heliopy.data.omni' has no attribute 'low'

### ISSUE THREAD

**Issue by Nnadih** [heliopython/heliopy#947]
Hi All, 
I am learning how to use the heliopy to analyse Omni data. For a start, I decided to run an already existing code I found online (https://docs.heliopy.org/en/0.6.4/auto_examples/plot_omni.html). For some unknown reason(s), I keep getting the AttributeError: module 'heliopy.data.omni' has no attribute 'low'. However, the documentation for the heliopy module (page 41)suggests that it has a 'low' attribute. Please, can someone help me to explain this and the way forward?

If I wish to use the high-resolution (1-minutes) Omni data what should I do? 

Thank you so much, as I look forward to your suggestions

**Comment by dstansby** [comment]
Hi there - `omni.low()` doesn't exist in heliopy, and the link to the examples is for an old version of heliopy which explains why it isn't working. If you try the example at https://docs.heliopy.org/en/stable/auto_examples/plot_omni.html#sphx-glr-auto-examples-plot-omni-py does it work fine?

**Comment by MohamedNedal** [comment]
Yes, I had the same issue, but the example that @dstansby  shared is working fine with me. The data doesn't include 'phi' and 'theta' angles of the IMF through. @dstansby  Could you please point to me where can I get those data?

**Comment by dstansby** [comment]
It gives you the magnetic field components, so you should be able to calculate the phi/theta angles yourself from those. I'm going to close this, as I think the original issue is solved now.
