### ISSUE TITLE
Data import checks for file existence, rather than most recent file update

### ISSUE THREAD

**Issue by mathewjowens** [heliopython/heliopy#951]
This is likely only an issue for OMNI data, where yearly datafiles are routinely updated. 

If OMNI data for a given year is downloaded in January, then in December a user requests the updated data, no update is performed, as the yearly file already exists. The user can manually delete the existing yearly file. But if it's straight forward to check the last updated date of the target and existing files, that would be preferable.

**Comment by dstansby** [comment]
👋 Thanks for opening this issue. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this issue know.

**Comment by dstansby** [comment]
I'm in the process of archiving heliopy, so am going to mark this as "won't fix" and close.
