### ISSUE TITLE
Directory of the imported data 

### ISSUE THREAD

**Issue by MohamedNedal** [heliopython/heliopy#956]
Hello, 
Please I would like to know where can I find the downloaded data locally?

**Comment by dstansby** [comment]
Does https://docs.heliopy.org/en/stable/auto_examples/data_inventory.html#sphx-glr-auto-examples-data-inventory-py help? It should print the directory the data is in, along with how much data you have.

**Comment by MohamedNedal** [comment]
Yes, exactly. Thanks a lot!
