### ISSUE TITLE
PSP FIELDS data v02 not supported

### ISSUE THREAD

**Issue by AyrisA** [heliopython/heliopy#985]
As of October 2020, the PSP FIELDS data files at CDAWeb have moved to version 2 and the current implementation fails to find them.

My local workaround is to adjust the fname for the 1min loader in the same style as you use for the SPC data:
(This will likely work for the other FIELDS time resolutions, but have not tested it)
```
     def fname(self, interval):
         datestr = interval.start.strftime('%Y%m%d')
-        return f'psp_fld_l2_mag_rtn_1min_{datestr}_v01.cdf'
+        if interval.start < datetime(2020, 10, 1):
+            version = '01'
+        else:
+            version = '02'
+        return f'psp_fld_l2_mag_rtn_1min_{datestr}_v{version}.cdf'
```

**Comment by rlaker** [comment]
I think this problem now extends to all FIELDS data on CDAWeb - i.e. they have gone back through all encounters and made every file version 2.

**Comment by dstansby** [comment]
Thanks for reporting - this should be fixed in https://github.com/heliopython/heliopy/pull/988, which I'll put in a bugfix release shortly.
